(function(){
var n=[
{id:369,name:"ONI TACO 池袋店",area:"東京",neighborhood:"豊島区南池袋",real:true,style:"沖縄タコス専門",price:"¥",score:84,reviews:42,emoji:"👹",tags:["沖縄発","コンフィ肉","低温調理","2025年オープン"],desc:"沖縄発のタコス＆タコライス専門店が2025年11月に池袋東口にオープン。メキシコ伝統の低温調理で仕上げたジューシーなコンフィ肉が特徴で、本場沖縄の味を東京で楽しめる。",address:"東京都豊島区南池袋2-14-1",hours:"11:00〜15:00 / 17:00〜22:00",closed:"月曜（祝日は営業）",tabelogScore:3.10},
{id:370,name:"ニコのタコス",area:"東京",neighborhood:"豊島区西池袋",real:true,style:"手作りタコス",price:"¥",score:86,reviews:65,emoji:"🌮",tags:["自家製トルティーヤ","手作り","テラス席","キャッシュレス"],desc:"池袋駅西口C3出口から徒歩3分。自家製生地のトルティーヤを一つ一つ手作りし、タコミートや具材も保存料を使わず手作りにこだわる。テラスで昼飲みもできる人気タコス屋。",address:"東京都豊島区西池袋3-33-17 東武西池袋サンライトマンション",hours:"11:00〜21:30（LO 20:30）",closed:"不定休",tabelogScore:3.35},
{id:371,name:"tacos trap'",area:"東京",neighborhood:"新宿区新宿御苑前",real:true,style:"タコス専門",price:"¥¥",score:87,reviews:75,emoji:"🪤",tags:["常時15種タコス","カルニータス","ビーガン対応","メスカル"],desc:"新宿御苑前のタコス専門店。常時15種類のタコスを用意し、豚肉をオレンジジュースでじっくり煮込んだポーク・カルニータスが看板。ビーガンタコスやメスカルも充実。",address:"東京都新宿区新宿1-20-6 石原共同ビル1F",hours:"12:00〜23:00（LO 22:30）",closed:"不定休",tabelogScore:3.45},
{id:372,name:"カーサテキーラ Tokyo",area:"東京",neighborhood:"新宿区歌舞伎町",real:true,style:"本格メキシカンバル",price:"¥¥¥",score:85,reviews:60,emoji:"🥃",tags:["コマル鉄板日本初","手作りトルティーヤ","テキーラ","歌舞伎町"],desc:"JR新宿駅から徒歩5分の本格メキシカンバル。メキシコの屋台で使われる丸い凸状の鉄板『コマル』を日本初導入し、目の前で手作りトルティーヤと具材を焼き上げる臨場感が魅力。",address:"東京都新宿区歌舞伎町1-7-5 トーシンビルB1F",hours:"16:00〜24:00",closed:"年末年始"},
{id:373,name:"Mexican Dining AVOCADO",area:"東京",neighborhood:"新宿区新宿三丁目",real:true,style:"メキシカンダイニング",price:"¥¥",score:83,reviews:55,emoji:"🥑",tags:["アボカド食べ放題","タコスプレート","五穀米タコライス"],desc:"新宿三丁目の色彩あふれるメキシカンダイニング。自家製トルティーヤのタコスプレートと五穀米タコライスがランチの人気メニュー。アボカド食べ放題付きプランも好評。",address:"東京都新宿区新宿3-9-4 2F",hours:"月〜金12:00〜15:00/17:00〜23:00、土11:30〜15:00/17:00〜23:00、日祝11:30〜15:00/17:00〜22:00",closed:"不定休"},
{id:374,name:"EL CARACOL",area:"東京",neighborhood:"新宿区四谷三丁目",real:true,style:"メキシカンバル",price:"¥¥",score:85,reviews:48,emoji:"🐚",tags:["屋台風タコス","メキシコ伝統料理","四谷三丁目"],desc:"四谷三丁目の隠れ家メキシカンバル。屋台風の本格タコスやメキシコの伝統料理を小さな店内で楽しめる。メキシコ現地の味を忠実に再現した料理が評判。",address:"東京都新宿区四谷4-10 金子ビル1F",hours:"火〜土17:00〜22:30（LO 21:30）",closed:"月曜・日曜",tabelogScore:3.40},
{id:375,name:"WIRED TACOS CLUB TOKYO",area:"東京",neighborhood:"港区高輪（品川駅）",real:true,style:"メキシカンダイナー",price:"¥¥",score:84,reviews:45,emoji:"🎸",tags:["TOKYO CRAZY STYLE","クラフトビール","2025年オープン","92席"],desc:"2025年2月に品川駅高輪口にオープンしたWIRED CAFE新業態。国産食材とメキシコの伝統を融合させた'TOKYO CRAZY STYLE'タコスが特徴。江戸前穴子タコスなどユニークなメニューも。",address:"東京都港区高輪4-10-18 ウイング高輪WEST2 2F",hours:"11:00〜23:00",closed:"不定休"},
{id:376,name:"FONDA MEXICANA New York",area:"東京",neighborhood:"中央区銀座",real:true,style:"モダンメキシカン",price:"¥¥¥",score:88,reviews:80,emoji:"🗽",tags:["NY発日本初上陸","モダンメキシカン","2024年オープン","銀座"],desc:"2024年6月にNYから日本初上陸したモダンメキシカン。銀座グランベルスクエア2階に位置し、NYで愛されたアーバンメキシカンの味をそのまま東京で再現。洗練された空間と本格タコスが魅力。",address:"東京都中央区銀座7-2-18 GRANBELL SQUARE 2F",hours:"月〜金11:30〜15:00/17:30〜22:30、土日祝11:00〜15:00/17:00〜22:00",closed:"不定休",tabelogScore:3.50},
{id:377,name:"TACO RICO 大手町ビル店",area:"東京",neighborhood:"千代田区大手町",real:true,style:"タコス＆ブリトー",price:"¥",score:82,reviews:40,emoji:"🏢",tags:["ファストカジュアル","手作り食材","テイクアウト","大手町"],desc:"港区で4店舗展開するタコス＆ブリトー専門チェーンの5号店として2023年12月にオープン。手作り食材にこだわったファストカジュアルスタイルで、ビジネスマンのランチに人気。",address:"東京都千代田区大手町1-6-1 大手町ビルB2F",hours:"11:00〜20:00",closed:"土日祝"},
{id:378,name:"をゲタコス",area:"東京",neighborhood:"足立区北千住",real:true,style:"タコス＆バー",price:"¥¥",score:85,reviews:58,emoji:"🧔",tags:["手作り生地","千住タコス","テラス席","昼飲み"],desc:"北千住駅西口から徒歩7分。生地から手作りの本格タコスが自慢で、巨大な『千住タコス』が名物。昼はランチ、夜はバーとして営業し、テラス席も完備。下町の陽気なタコス酒場。",address:"東京都足立区千住3-56 高橋ビル1F",hours:"火〜日11:30〜24:00（月曜17:00〜）",closed:"なし（月曜はディナーのみ）",tabelogScore:3.25},
{id:379,name:"タコスビーム",area:"東京",neighborhood:"板橋区上板橋",real:true,style:"沖縄タコス＆タコライス",price:"¥",score:80,reviews:30,emoji:"⚡",tags:["沖縄式タコス","タコライス","沖縄そば","オリオンビール"],desc:"上板橋駅から徒歩5分。沖縄のタコスとタコライスを中心に、沖縄そばやフーチャンプルーも提供。レッドソースとヨーグルトベースのホワイトソースから選べるのが特徴。",address:"東京都板橋区桜川1丁目",hours:"11:00〜22:00",closed:"不定休",tabelogScore:3.22},
{id:380,name:"EL-POCO",area:"東京",neighborhood:"板橋区志村坂上",real:true,style:"テックスメックス",price:"¥¥",score:81,reviews:35,emoji:"🤠",tags:["1977年創業","老舗","ステーキ","タコス","テックスメックス"],desc:"1977年創業、板橋区で約50年愛されるテックスメックスの老舗。自家製チョリソーやタコス、ステーキなどアメリカンメキシカンの定番が揃う。カウボーイハットが飾られた店内が印象的。",address:"東京都板橋区小豆沢2-16-5",hours:"17:30〜23:00（LO 22:30）",closed:"不定休"},
{id:381,name:"3Bタコス",area:"東京",neighborhood:"台東区田原町",real:true,style:"タコス＆タコロール",price:"¥",score:83,reviews:50,emoji:"🅱️",tags:["リーズナブル","タコロール","ボリューム満点","テイクアウト"],desc:"田原町駅近くのリーズナブルっ��タコス店。400円台からの手頃な価格でボリューム満点のタコスとタコロール（ブリトー）が楽しめる。テイクアウトにも対応した下町の人気店。",address:"東京都台東区寿3-16-14 原ビル1F",hours:"11:00〜21:00（LO 20:30）",closed:"月曜",tabelogScore:3.30}
];
if(window.stores){n.forEach(function(s){var exists=window.stores.some(function(e){return e.id===s.id});if(!exists)window.stores.push(s)});if(typeof window.renderStores==='function')window.renderStores();}else{window.storesExtra6=n;}
})();
