(function(){
var n=[
{id:341,name:"TACOS PEPE",area:"富山",neighborhood:"富山市婦中町",real:true,style:"タコス専門",price:"¥",score:85,reviews:48,emoji:"🌮",tags:["タコス専門","手作りトルティーヤ","富山産食材"],desc:"サンディエゴ出身のペペさんが経営する本格タコス専門店。100%トウモロコシの手作りトルティーヤを使用し、白エビなど富山産食材も活用した地産地消のタコスが人気。",address:"富山県富山市婦中町西本郷653-6",hours:"11:00〜20:00（日祝は17:00まで）",closed:"不定休",tabelogScore:3.30},
{id:342,name:"tacos y margarita",area:"山形",neighborhood:"山形市本町",real:true,style:"本格メキシコ料理",price:"¥¥",score:83,reviews:40,emoji:"🍹",tags:["メキシコ料理","マルガリータ","手作りデザート"],desc:"東京の有名メキシコ料理店で修行したオーナーが2024年12月にオープン。本場の味と日本人向けアレンジを両立し、フランやチュロスなど手作りデザートも充実。",address:"山形県山形市本町1-4-23",hours:"11:00〜14:00 / 17:00〜23:00",closed:"不定休",tabelogScore:3.40},
{id:343,name:"アスタコス",area:"佐賀",neighborhood:"佐賀市神野東",real:true,style:"沖縄タコス専門",price:"¥",score:82,reviews:35,emoji:"🌮",tags:["タコス専門","沖縄式","パリパリ食感","手作り"],desc:"沖縄のタコス店で経験を積んだオーナーが2023年にオープン。本場沖縄のパリパリ食感タコスをベースに、サルサも肉も生地も全て手作りのこだわり店。",address:"佐賀県佐賀市神野東3-7-24",hours:"11:00〜20:00",closed:"月曜・祝日"},
{id:344,name:"フリーダム タコス ベース",area:"岡山",neighborhood:"岡山市中区竹田",real:true,style:"無添加タコス",price:"¥",score:80,reviews:30,emoji:"🌿",tags:["無添加","岡山産食材","テイクアウト","玄米"],desc:"岡山県産の米・小麦・パクチーを使用した無添加タコスが特徴。玄米や全粒粉など精製されていない素材を活用した体に優しいメキシカン。Uber Eatsにも対応。",address:"岡山県岡山市中区竹田",hours:"11:00〜19:00",closed:"月曜"},
{id:345,name:"トランキーロタコス 父母ヶ浜店",area:"香川",neighborhood:"三豊市仁尾町",real:true,style:"和風タコス",price:"¥¥",score:84,reviews:55,emoji:"🏖️",tags:["タコス専門","海景観","日本人向けアレンジ"],desc:"メキシコ和食店で料理人をしていた大将がプロデュース。草屋根が特徴のカフェ&レストランで、父母ヶ浜の海を眺めなから日本人好みにアレンジされたタコスを楽しめる。",address:"香川県三豊市仁尾町仁尾乙266-15",hours:"平日11:00〜15:30 / 土日祝11:00〜17:00",closed:"月曜（祝日の場合は翌日）"},
{id:346,name:"SANBARCO",area:"宮崎",neighborhood:"宮崎市青島",real:true,style:"本格メキシコ料理",price:"¥¥",score:86,reviews:80,emoji:"🌊",tags:["自家製トルティーヤ","自然派ワイン","本場仕込み"],desc:"ギーノーシェフが西洋料理の経験を生かし、本場メキシコの手法で作る自家製トルティーヤとサルサが自慢。青島の絶好のロケーションでいただく本格タコス。",address:"宮崎県宮崎市青島2-8-11",hours:"月火金日12:00〜15:00・18:00〜21:00",closed:"水曜・木曜",tabelogScore:3.50},
{id:347,name:"テキラッチョ",area:"大分",neighborhood:"大分市大手町",real:true,style:"メキシコ料理バー",price:"¥¥",score:81,reviews:42,emoji:"🥃",tags:["テキーラ40種","タコス","ケサディージャ"],desc:"メキシコに移住した経歴を持つマスターが本格メキシコ料理を提供。テキーラ40種類以上を揃え、タコスやケサディージャなどメニューも充実した本格派。",address:"大分県大分市大手町1-1-8 大手佐藤ビル2F",hours:"18:00〜翌2:00",closed:"不定休"},
{id:348,name:"HOLA! TACOS",area:"岩手",neighborhood:"山田町織笠",real:true,style:"海鮮タコス",price:"¥",score:83,reviews:38,emoji:"🦪",tags:["タコス専門","山田湾カキ","地元食材"],desc:"山田湾の新鮮なカキを使った特別なタコスが名物。地元の朝採りカキを使用した季節限定メニューも人気で、海の幸を活かした独自のタコスを提供。",address:"岩手県下閉伊郡山田町織笠11-302-1",hours:"11:00〜19:00",closed:"水曜"},
{id:349,name:"メシカ",area:"和歌山",neighborhood:"和歌山市新中通",real:true,style:"本格メキシコ料理",price:"¥¥",score:84,reviews:45,emoji:"🫔",tags:["100%ブルーコーン","手作りトルティーヤ","本場仕込み"],desc:"東京のメキシコ料理店で修行後、メキシコで学んだオーナーが営む本格店。100%トウモロコシ使用の手作りトルティーヤと本場仕込みのサルサが絶品。",address:"和歌山県和歌山市新中通2-37-37 メゾン雅1F",hours:"ランチ11:00〜14:00（日のみ）/ ディノー18:00〜21:30",closed:"月曜"},
{id:350,name:"Mexican Comedor gurico",area:"福島",neighborhood:"福島市",real:true,style:"メキシコ料理",price:"¥¥",score:82,reviews:35,emoji:"🌶️",tags:["メキシコ料理","テキーラ","タコス"],desc:"JR福島駅東口より徒歩8分。メキシコ料理やメキシコ縁のお酒を提供。タコス、トルティーヤ、メキシコならではのおつまみが多数揃う本格派。",address:"福島県福島市",hours:"17:00〜23:00",closed:"月曜"},
{id:351,name:"non's TACOS",area:"福島",neighborhood:"福島市",real:true,style:"タコスバー",price:"¥¥",score:81,reviews:30,emoji:"🌮",tags:["テキーラマエストロ","タコス","メキシカン"],desc:"テキーラマエストロの資格を持つギーノーが厳選したメキシコのお酒と自慢のタコスを提供。ノンズタコス2個600円が看板メニュー。",address:"福島県福島市",hours:"17:00〜23:00",closed:"月曜"},
{id:352,name:"メキシカンキッチン・バルバ",area:"茨城",neighborhood:"古河市",real:true,style:"本格メキシカン",price:"¥¥",score:82,reviews:32,emoji:"🫓",tags:["手焼きトルティーヤ","タコス","ブリトー"],desc:"とうもろこし粉を使用した手焼きトルティーヤにこだわるメキシカン料理店。ビーフ・ポーク・チリビーンズなどバリエーション豊かなタコスとブリトーを提供。",address:"茨城県古河市",hours:"17:00〜23:00",closed:"月曜"},
{id:353,name:"Thunder Tacos",area:"栃木",neighborhood:"宇都宮市",real:true,style:"LAスタイルメキシカン",price:"¥¥",score:83,reviews:40,emoji:"⚡",tags:["LAスタイル","ブリトー","テイクアウト"],desc:"LAスタイルのモダンメキシカンカフェ＆レストラン。本格的なタコスとブリトーを提供し、テイクアウトの事前予約も対応。雷都・宇都宮のタコスの新名所。",address:"栃木県宇都宮市",hours:"11:30〜14:30 / 17:00〜22:00",closed:"月曜"},
{id:354,name:"メキシカン酒場 MUCHO AMIGO",area:"静岡",neighborhood:"浜松市中央区",real:true,style:"メキシカン酒場",price:"¥¥",score:85,reviews:50,emoji:"🍻",tags:["自家製トルティーヤ","11種タコス","メキシコ産マサ粉"],desc:"浜松駅から徒歩5分。最高品質のメキシコ産マサ粉で作る自家製トルティーヤが自慢。11種類の本場メキシコ名物タコスとオリジノルタコスを提供する専門酒場。",address:"静岡県浜松市中央区田町",hours:"17:00〜23:00",closed:"月曜"},
{id:355,name:"覇王樹（サボテン）",area:"大阪",neighborhood:"大阪市西区北堀江",real:true,style:"本格メキシコ料理",price:"¥¥¥",score:88,reviews:95,emoji:"🌵",tags:["メキシコ人シェフ","本格派","モレ","スワデロ"],desc:"メキシコのコリマ州から来日したギーノーシェフが2016年にギープン。牛肉を煮込んだスワデロやモレなど、日本では珍しい本格メキシコ料理の数々が味わえる名店。",address:"大阪府大阪市西区北堀江",hours:"17:00〜23:00",closed:"月曜",tabelogScore:3.55},
{id:356,name:"CANTINA RIMA",area:"大阪",neighborhood:"大阪市北区中崎町",real:true,style:"タコス専門",price:"¥¥",score:86,reviews:70,emoji:"🫔",tags:["自家製トルティーヤ","13種タコス","毎朝手作り"],desc:"中崎町駅近く。毎朝手でこねて作る自家製トルティーヤが自慢で、13種類の具材から選べる多彩なタコスメニューが魅力。ランチのタコスプレートが人気。",address:"大阪府大阪市北区中崎町",hours:"11:30〜15:00 / 17:00〜23:00",closed:"月曜"},
{id:357,name:"TACOstore 森",area:"兵庫",neighborhood:"加古川市",real:true,style:"本格メキシコ料理",price:"¥¥",score:84,reviews:45,emoji:"🌮",tags:["フィッシュタコス","プレミアムテキーラ","2023年開店"],desc:"東京とメキシコで修行を重ねた店主が2023年4月にギープン。フィッシュタコスをはじめとする本格メキシコ料理とプレミアムテキーラが楽しめる注目の新店。",address:"兵庫県加古川市東加古川駅周辺",hours:"17:00〜23:00",closed:"月曜"},
{id:358,name:"dos tacos yasaka",area:"京都",neighborhood:"京都市東山区",real:true,style:"タコス専門",price:"¥¥",score:85,reviews:55,emoji:"⛩️",tags:["古民家","昼限定","観光客人気"],desc:"八坂神社の南、静かな路地裏に佇む古民家のタコス専門店。昼間限定営業で、海外からの観光客からも本場の味と評判。京都の風情とタコスの意外な調和が魅力。",address:"京都府京都市東山区八坂神社周辺",hours:"11:00〜17:00",closed:"不定休"},
{id:359,name:"メキシコ料理 ロシータ",area:"福岡",neighborhood:"福岡市博多区中洲",real:true,style:"老舗メキシコ料理",price:"¥¥",score:85,reviews:65,emoji:"🌹",tags:["老舗","テイクアウト","中洲名物"],desc:"中洲の名物テイクアウトとして不動の人気を誇るメキシコ料理店。3本1,200円のこだわりタコスが看板メニューで、地元民にも観光客にも愛される老舗。",address:"福岡県福岡市博多区中洲2-1-15 2F",hours:"17:00〜22:00",closed:"火曜"},
{id:360,name:"TACOMIA",area:"福岡",neighborhood:"福岡市中央区大手門",real:true,style:"メキシコ料理",price:"¥¥",score:83,reviews:50,emoji:"🌮",tags:["タコス","ブリトー","大濠公園"],desc:"大濠公園駅すぐそばのメキシコ料理店。タコスをはじめブリトーやナチョスなどメキシコのファストフードを手軽に楽しめる。ランチとディノーの2部制。",address:"福岡県福岡市中央区大手門3-5-8",hours:"11:30〜14:30 / 17:00〜20:30",closed:"月曜"},
{id:361,name:"メキシコレストラン トルタコス",area:"熊本",neighborhood:"熊本市",real:true,style:"メキシコ料理専門",price:"¥¥",score:84,reviews:45,emoji:"🫔",tags:["ハーフギーノー","タコス","ブリトー","テイクアウト"],desc:"メキシコと日本のハーフのギーノーシェフが作る本格メキシコ料理専門店。タコスやブリトーなどこだわりの一品料理をテイクアウトでも楽しめる。熊本の穴場名店。",address:"熊本県熊本市",hours:"11:00〜22:00",closed:"火曜"},
{id:362,name:"El Dorado",area:"長崎",neighborhood:"長崎市",real:true,style:"本場メキシコ料理",price:"¥¥",score:82,reviews:38,emoji:"🇲🇽",tags:["メキシコ人経営","本場タコス"],desc:"メキシコ人が作る本場のタコスを提供するレストラン。メキシカン料理とカラオケも楽しめる、長崎で貴重な本格メキシコ料理の店。",address:"長崎県長崎市",hours:"17:00〜23:00",closed:"月曜"},
{id:363,name:"ELtope",area:"北海道",neighborhood:"札幌市中央区大通",real:true,style:"メキシコ料理",price:"¥¥",score:86,reviews:60,emoji:"🐑",tags:["ラム肉タコス","メキシコ唐辛子","札幌"],desc:"札幌大通のメキシコ料理専門店。ラム肉のタコスが一番人気で、メキシコ唐辛子とスパイスで1日マリネし、じっくり焼いた後ホロホロになるまで煮込んだラム肉を使用。",address:"北海道札幌市中央区大通",hours:"17:00〜23:30",closed:"月曜"},
{id:364,name:"Burrito y Tacos 5884",area:"長野",neighborhood:"上伊那郡箕輪町",real:true,style:"ブリトー・タコス専門",price:"¥¥",score:83,reviews:35,emoji:"🌯",tags:["タコス専門","ブリトー","本場仕込み","リニューアル"],desc:"10年以上親しまれてきたメキシコ料理店が2025年にリニューアルオープン。本場仕込みのタコスとブリトーが主力で、信州の食材も取り入れた独自のメキシカンを提供。",address:"長野県上伊那郡箕輪町",hours:"11:00〜20:00",closed:"月曜"},
{id:365,name:"TACO FANATICO 久屋大通店",area:"名古屋",neighborhood:"名古屋市中区",real:true,style:"本格メキシカン",price:"¥¥",score:85,reviews:70,emoji:"🌮",tags:["本格メキシカン","中目黒発"],desc:"東京中目黒発祥の人気メキシカンタコス店。RAYARD Hisaya-odori Park内に位置し、本格的なメキシカンタコスを名古屋でも楽しめる。",address:"愛知県名古屋市中区久屋大通",hours:"11:00〜22:00",closed:"不定休"},
{id:366,name:"創作メキシコ料理 チャベリータ",area:"三重",neighborhood:"津市久居",real:true,style:"創作メキシコ料理",price:"¥¥",score:82,reviews:30,emoji:"🎨",tags:["創作メキシコ料理","ランチ","ディノー"],desc:"三重県津市久居にある創作メキシコ料理店。本場のレシピをベースに日本の食材でアレンジした独自のタコスとメキシコ料理を提供。ランチ・ディノー営業。",address:"三重県津市久居",hours:"11:30〜14:30 / 18:00〜22:00",closed:"月曜"},
{id:367,name:"LUCKY TACOS",area:"沖縄",neighborhood:"那覇市平和通り",real:true,style:"タコス専門",price:"¥",score:84,reviews:55,emoji:"🍀",tags:["塩タコス","沖縄の塩マース","子供OK"],desc:"那覇市平和通りに位置するタコス専門店。沖縄の塩『マース』を使った塩タコスが人気。自家製サルサはタバスコなしで子供も食べられるやさしい味わい。",address:"沖縄県那覇市平和通り",hours:"11:00〜20:00",closed:"月曜"},
{id:368,name:"赤とんぼ",area:"沖縄",neighborhood:"那覇市",real:true,style:"タコス・タコライス",price:"¥",score:87,reviews:90,emoji:"🔴",tags:["テイクアウト","人気店","売り切れ必至"],desc:"サンライズ那覇商店街のアーケード内。地元の人が次々と買いに訪れる大人気テイクアウト店。こだわりのタコライス・タコスは売り切れ必至の名物。",address:"沖縄県那覇市サンライズ那覇商店街",hours:"10:00〜18:00（売り切れ次第終了）",closed:"不定休"}
];
if(window.stores){n.forEach(function(s){var exists=window.stores.some(function(e){return e.id===s.id});if(!exists)window.stores.push(s)});if(typeof window.renderStores==='function')window.renderStores();}else{window.storesExtra5=n;}
})();
